name: web_image_downloader
description: Use this package to download / save images to your computer locally, when run in web.
version: 0.0.1
homepage: https://github.com/sivaprasadnk/WebImageDownloader

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: